// svelte/src/row.svelte
<script>
  export let color = {}

  import Header from './header.svelte'
  import Color from './color.svelte' 
</script>

<tr
  class='color-contrast-table__row'
  data-color={color.name}
  style="
    background: {color.value};
    color: {color.value};
  "
>
  <Header {...$$props} />

  {#each color.combinationScores as color, index}
    <Color {color} />
  {/each}
</tr>

// react/src/row.jsx
import React from 'react'
import PropTypes from 'prop-types'

import Header from './header.jsx'
import Color from './color.jsx'

const Row = props => {
  return (
    <tr
      className='color-contrast-table__row'
      data-color={color.name}
      style={{
        background: props.color.value,
        color: props.color.value
      }}
    >
      <Header {...props} />

      {props.color.combinationScores.map((color, index) => {
        return (
          <Color
            key={index}
            color={color}
          />
        )
      })}
    </tr>
  )
}

Row.propTypes = {
  color: PropTypes.object.isRequired,
  index: PropTypes.number.isRequired
}

export default Row
