// vue/src/table.vue
<script>  
  import Row from './row.vue'

  export default {
    name: 'Table',
    components: {
      Row
    },
    props: {
      colors: Array,
      useStyles: Boolean
    },
    methods: {
      namechange(index, value) { this.$emit('namechange', index, value) },
      valuechange(index, value) { this.$emit('valuechange', index, value) },
      inputblur(event) { this.$emit('inputblur', event) }
    }
  }

</script>

<template>
  <table
    class='color-contrast-table'
    v-bind:class="{ 'use-styles': useStyles }"
  >
    <tbody>
      <Row
        v-for="(color, index) in colors"
        :key="index"
        :index="index"
        :color="color"
        v-bind="$attrs"
        @namechange="namechange"
        @valuechange="valuechange"
        @inputblur="inputblur"
      />
    </tbody>
  </table>
</template>

// react/src/table.jsx
import React from 'react'
import PropTypes from 'prop-types'

import Row from './row.jsx'

const Table = props => {
  return (
    <table className='color-contrast-table'>
      <tbody>
        {props.colors.map((color, index) => {
          return (
            <Row
              key={index}
              index={index}
              color={color}
              {...props}
            />
          )
        })}
      </tbody>
    </table>
  )
}

Table.propTypes = {
  colors: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string,
      value: PropTypes.string
    }).isRequired
  ).isRequired
}

export default Table
