// vue/src/edit-name.vue
<script>
  export default {
    name: 'EditName',
    props: {
      value: String,
      index: Number
    }
  }
</script>

<template>
  <label class='color-contrast-table__header-label color-contrast-table__header-label--edit-name'>
    <span>
      {{ value }}
    </span>
    <input
      type='text'
      :title="`${value} name`"
      :value="value"
      @input="$emit('namechange', index, $event.target.value)"
      @blur="$emit('inputblur', $event)"
    />
  </label>
</template>

// svelte/src/edit-name.svelte
<script>
  export let value = ''
  export let index = ''
  export let onChange
  export let onBlur
</script>

<label class='color-contrast-table__header-label color-contrast-table__header-label--edit-name'>
  <span>
    {value}
  </span>
  <input
    type='text'
    title={`${value} name`}
    value={value}
    on:input={event => onChange(index, event.target.value)}
    on:blur={event => onBlur(event)}
  />
</label>
