// react/src/row.jsx
import React from 'react'
import PropTypes from 'prop-types'

import Header from './header.jsx'
import Color from './color.jsx'

const Row = props => {
  return (
    <tr
      className='color-contrast-table__row'
      data-color={color.name}
      style={{
        background: props.color.value,
        color: props.color.value
      }}
    >
      <Header {...props} />

      {props.color.combinationScores.map((color, index) => {
        return (
          <Color
            key={index}
            color={color}
          />
        )
      })}
    </tr>
  )
}

Row.propTypes = {
  color: PropTypes.object.isRequired,
  index: PropTypes.number.isRequired
}

export default Row

// vue/src/row.vue
<script>  
  import Header from './header.vue'
  import Color from './color.vue'

  export default {
    name: 'Row',
    components: {
      Header,
      Color
    },
    props: {
      color: Object,
      index: Number
    },
    methods: {
      namechange(index, value) { this.$emit('namechange', index, value) },
      valuechange(index, value) { this.$emit('valuechange', index, value) },
      inputblur(event) { this.$emit('inputblur', event) }
    }
  }
</script>

<template>
  <tr
    class='color-contrast-table__row'
    data-color="color.name"
    :style="{ 
      'background': color.value,
      'color': color.value
    }"
  >
    <Header
      :color="color"
      :index="index"
      v-bind="$attrs"
      @namechange="namechange"
      @valuechange="valuechange"
      @inputblur="inputblur"
    />

    <Color
      v-for="(color, index) in color.combinationScores"
      :key="index"
      :color="color"
    />
  </tr>
</template>
